#! /usr/bin/env python
# encoding: utf-8

#Maybe not necessary ...
import misc, gnome

#Subsitute the environnement variable
applets=bld.create_obj('subst')
applets.source = 'taskman.desktop.in.in'
applets.target = 'taskman.desktop.in'
applets.dict = {'PKGDATADIR': bld.env()['PKGDATADIR']}
applets.fun = misc.subst_func
#Subsitute must be apply before intltool
applets.prio = 1

#Use intltool
applets=bld.create_obj('intltool_in')
applets.source  = 'taskman.desktop.in'
applets.destvar = 'LIBDIR'
applets.subdir  = '/awn/applets'
applets.podir   = '../po'
applets.flags   = '-d'
