.TH AVANT-WINDOW-NAVIGATOR 1 "June 25, 2007"
.SH NAME
avant-window-navigator \- A MacOS X like panel for GNOME

.SH SYNOPSIS
.B avant-window-navigator

.SH DESCRIPTION
\fBavant-window-navigator\fP is a dock-like bar which sits at the bottom of the screen. It has support for launchers, task lists, and applets. You can drag and drop icon of the main menu of GNOME to create launchers. When you clic on this launcher, the window is captured like in the windows list of the gnome-panel. The applications can send messages via DBUS and change their icon (like the Rhythmbox icon can become the covert art for the current song). Avant-window-navigator can also be extended by some applets(like a trash applet, a clock ...). See the home page of the project for more informations.

.SH AUTHOR
avant-window-navigator was written by Neil Jagdish Patel <njpatel@gmail.com>.
.PP
This manual page was written by Julien Lavergne <julien.lavergne@gmail.com>,
for the Debian project (but may be used by others).
