.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH AWN-MANAGER 1 "June 25, 2007"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
awn-manager \- A manager for the preferences of avant-window-navigator
.SH SYNOPSIS
.B The awn-manager provide a simple way to configure avant-window-navigator. You can manage preferences, themes, applets and launchers.
.RI avant-manager Launch the preference window
.br
.SH DESCRIPTION
\fBavant-window-navigator\fP awn-manager provide a simple way to configure avant-window-navigator. You can manage preferences, themes, applets and launchers with a graphical interface.
.SH AUTHOR
awn-manager was written by Neil Jagdish Patel <njpatel@gmail.com>.
.PP
This manual page was written by Julien Lavergne <julien.lavergne@gmail.com>,
for the Debian project (but may be used by others).
