.TH AWN-LAUNCHER-EDITOR 1 "February 17, 2008"
.SH NAME
awn-launcher-editor \- A launcher editor for avant-window-navigator

.SH SYNOPSIS
.B awn-launcher-editor

.SH DESCRIPTION
\fBawn-launcher-editor\fP provide a simple way to configure and edit the launchers of avant-window-navigator. You can change the name, the description, the command and the icon of the launcher.

.SH AUTHOR
awn-launcher-editor was written by Mark Lee <avant-wn@lazymalevolence.com>.
.PP
This manual page was written by Julien Lavergne <julien.lavergne@gmail.com>,
for the Debian project (but may be used by others).
