.TH AWN-AUTOSTART 1 "January 20, 2009"
.SH NAME
awn-autostart \- An script to start avant-window-navigator when session start.

.SH SYNOPSIS
.B awn-autostart

.SH DESCRIPTION
\fBawn-autostart\fP is a script to start avant-window-navigator when the 
session start. See man avant-window-navigator for more informations.

.SH AUTHOR
awn-autostart was written by Neil Jagdish Patel <njpatel@gmail.com>.
.PP
This manual page was written by Julien Lavergne <julien.lavergne@gmail.com>,
for the Debian project (but may be used by others).
