.TH AWN-APPLET 1 "June 25, 2007"
.SH NAME
awn-applet \- A tool for launching applets of avant-window-navigator

.SH SYNOPSIS
.B awn-applet

.SH DESCRIPTION
\fBawn-applet\fP is a tool for launching applets of avant-window-navigator. Please see man avant-window-navigator for more details.

.SH AUTHOR
awn-applet was written by Neil Jagdish Patel <njpatel@gmail.com>.
.PP
This manual page was written by Julien Lavergne <julien.lavergne@gmail.com>,
for the Debian project (but may be used by others).
