.TH AWN-MANAGER 1 "June 25, 2007"
.SH NAME
awn-manager \- A manager for the preferences of avant-window-navigator

.SH SYNOPSIS
.B awn-manager

.SH DESCRIPTION
\fBawn-manager\fP provide a simple way to configure avant-window-navigator. You can manage preferences, themes, applets and launchers with a graphical interface.

.SH AUTHOR
awn-manager was written by Neil Jagdish Patel <njpatel@gmail.com>.
.PP
This manual page was written by Julien Lavergne <julien.lavergne@gmail.com>,
for the Debian project (but may be used by others).
