.TH AWN-APPLETS-MIGRATION 1 "February 7, 2009"
.SH NAME
awn-applets-migration \- A script which converts old configuration path for 
avant-window-navigator's applets.

.SH SYNOPSIS
.B awn-applets-migration

.SH DESCRIPTION
\fBawn-applets-migration\fP is a script which converts old configuration path 
for avant-window-navigator's applets.

.SH AUTHOR
awn-applets-migration was written by Julien Lavergne <julien.lavergne@gmail.com>.
.PP
This manual page was written by Julien Lavergne <julien.lavergne@gmail.com>,
for the Debian project (but may be used by others).
