.TH AWN-SCHEMA-TO-GCONF 1 "February 17, 2008"
.SH NAME
awn-schema-to-gconf \- A script which converts keyfile-based schemas into GConf schemas for avant-window-navigator.

.SH SYNOPSIS
.B awn-schema-to-gconf

.SH DESCRIPTION
\fBawn-schema-to-gconf\fP is a script which converts keyfile-based schemas into GConf schemas. It used for applets of avant-window-navigator.

.SH AUTHOR
awn-launcher-editor was written by Mark Lee <avant-wn@lazymalevolence.com>.
.PP
This manual page was written by Julien Lavergne <julien.lavergne@gmail.com>,
for the Debian project (but may be used by others).
