/* awn-panel-dispatcher.h generated by valac 0.12.1, the Vala compiler, do not modify */


#ifndef __AWN_PANEL_DISPATCHER_H__
#define __AWN_PANEL_DISPATCHER_H__

#include <glib.h>
#include <glib-object.h>
#include <dbus/dbus-glib.h>
#include <dbus/dbus-glib-lowlevel.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>
#include "awn-panel.h"
#include <vector>

#ifdef __cplusplus
extern "C" {
#endif

#define AWN_TYPE_PANEL_DBUS_INTERFACE (awn_panel_dbus_interface_get_type ())
#define AWN_PANEL_DBUS_INTERFACE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AWN_TYPE_PANEL_DBUS_INTERFACE, AwnPanelDBusInterface))
#define AWN_IS_PANEL_DBUS_INTERFACE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AWN_TYPE_PANEL_DBUS_INTERFACE))
#define AWN_PANEL_DBUS_INTERFACE_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), AWN_TYPE_PANEL_DBUS_INTERFACE, AwnPanelDBusInterfaceIface))

typedef struct _AwnPanelDBusInterface AwnPanelDBusInterface;
typedef struct _AwnPanelDBusInterfaceIface AwnPanelDBusInterfaceIface;

#define AWN_TYPE_PANEL_DISPATCHER (awn_panel_dispatcher_get_type ())
#define AWN_PANEL_DISPATCHER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AWN_TYPE_PANEL_DISPATCHER, AwnPanelDispatcher))
#define AWN_PANEL_DISPATCHER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), AWN_TYPE_PANEL_DISPATCHER, AwnPanelDispatcherClass))
#define AWN_IS_PANEL_DISPATCHER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AWN_TYPE_PANEL_DISPATCHER))
#define AWN_IS_PANEL_DISPATCHER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), AWN_TYPE_PANEL_DISPATCHER))
#define AWN_PANEL_DISPATCHER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), AWN_TYPE_PANEL_DISPATCHER, AwnPanelDispatcherClass))

struct AwnImageStruct {
    int32_t width;
    int32_t height;
    int32_t rowstride;
    bool has_alpha;
    int32_t bits_per_sample;
    int32_t num_channels;
    std::vector<char> pixel_data;
};

struct _AwnPanelDBusInterfaceIface {
    GTypeInterface parent_iface;
    void (*add_applet)(AwnPanelDBusInterface* self, const gchar* desktop_file, GError** error);
    void (*delete_applet)(AwnPanelDBusInterface* self, const gchar* uid, GError** error);
    gint64(*docklet_request)(AwnPanelDBusInterface* self, gint min_size, gboolean shrink, gboolean expand, GError** error);
    gchar** (*get_inhibitors)(AwnPanelDBusInterface* self, int* result_length1, GError** error);
    void (*get_snapshot)(AwnPanelDBusInterface* self, AwnImageStruct* result, GError** error);
    guint(*inhibit_autohide)(AwnPanelDBusInterface* self, const char* sender, const gchar* app_name, const gchar* reason, GError** error);
    void (*uninhibit_autohide)(AwnPanelDBusInterface* self, guint cookie, GError** error);
    void (*set_applet_flags)(AwnPanelDBusInterface* self, const gchar* uid, gint flags, GError** error);
    void (*set_glow)(AwnPanelDBusInterface* self, const char* sender, gboolean activate, GError** error);
    gdouble(*get_offset_modifier)(AwnPanelDBusInterface* self);
    gint(*get_max_size)(AwnPanelDBusInterface* self);
    gint(*get_offset)(AwnPanelDBusInterface* self);
    void (*set_offset)(AwnPanelDBusInterface* self, gint value);
    gint(*get_path_type)(AwnPanelDBusInterface* self);
    gint(*get_position)(AwnPanelDBusInterface* self);
    void (*set_position)(AwnPanelDBusInterface* self, gint value);
    gint(*get_size)(AwnPanelDBusInterface* self);
    void (*set_size)(AwnPanelDBusInterface* self, gint value);
    gint64(*get_panel_xid)(AwnPanelDBusInterface* self);
};

struct AwnPanelDispatcherPrivate;

struct AwnPanelDispatcher {
    GObject parent_instance;
    AwnPanelDispatcherPrivate* priv;
};

struct AwnPanelDispatcherClass {
    GObjectClass parent_class;
};

AwnPanelDBusInterface* awn_panel_dbus_interface_dbus_proxy_new(DBusGConnection* connection, const char* name, const char* path);
GType awn_panel_dbus_interface_get_type(void) G_GNUC_CONST;
void awn_panel_dbus_interface_add_applet(AwnPanelDBusInterface* self, const gchar* desktop_file, GError** error);
void awn_panel_dbus_interface_delete_applet(AwnPanelDBusInterface* self, const gchar* uid, GError** error);
gint64 awn_panel_dbus_interface_docklet_request(AwnPanelDBusInterface* self, gint min_size, gboolean shrink, gboolean expand, GError** error);
gchar** awn_panel_dbus_interface_get_inhibitors(AwnPanelDBusInterface* self, int* result_length1, GError** error);
void awn_panel_dbus_interface_get_snapshot(AwnPanelDBusInterface* self, AwnImageStruct* result, GError** error);
guint awn_panel_dbus_interface_inhibit_autohide(AwnPanelDBusInterface* self, const char* sender, const gchar* app_name, const gchar* reason, GError** error);
void awn_panel_dbus_interface_uninhibit_autohide(AwnPanelDBusInterface* self, guint cookie, GError** error);
void awn_panel_dbus_interface_set_applet_flags(AwnPanelDBusInterface* self, const gchar* uid, gint flags, GError** error);
void awn_panel_dbus_interface_set_glow(AwnPanelDBusInterface* self, const char* sender, gboolean activate, GError** error);
gdouble awn_panel_dbus_interface_get_offset_modifier(AwnPanelDBusInterface* self);
gint awn_panel_dbus_interface_get_max_size(AwnPanelDBusInterface* self);
gint awn_panel_dbus_interface_get_offset(AwnPanelDBusInterface* self);
void awn_panel_dbus_interface_set_offset(AwnPanelDBusInterface* self, gint value);
gint awn_panel_dbus_interface_get_path_type(AwnPanelDBusInterface* self);
gint awn_panel_dbus_interface_get_position(AwnPanelDBusInterface* self);
void awn_panel_dbus_interface_set_position(AwnPanelDBusInterface* self, gint value);
gint awn_panel_dbus_interface_get_size(AwnPanelDBusInterface* self);
void awn_panel_dbus_interface_set_size(AwnPanelDBusInterface* self, gint value);
gint64 awn_panel_dbus_interface_get_panel_xid(AwnPanelDBusInterface* self);
GType awn_panel_dispatcher_get_type(void) G_GNUC_CONST;
AwnPanelDispatcher* awn_panel_dispatcher_new(AwnPanel* panel);
AwnPanelDispatcher* awn_panel_dispatcher_construct(GType object_type, AwnPanel* panel);
AwnPanel* awn_panel_dispatcher_get_panel(AwnPanelDispatcher* self);

#ifdef __cplusplus
} // extern "C"
#endif

#endif
